module.exports = {
  catalogURL: 'https://cdc-catalog.cfapps.eu10.hana.ondemand.com',
  firebaseDBUrl: 'https://gigya-catalog.firebaseio.com',
  storageBucket: 'gigya-catalog.appspot.com',
  projectId: 'gigya-catalog',
  allFields: [
    "AM",
    "APIKey",
    "CMS",
    "Category",
    "CentralizedLoginSSO",
    "Country",
    "CustomFlows",
    "Customer",
    "Description",
    "FrontEndLibraries",
    "GoLiveDate",
    "IC",
    "Implementation",
    "ImplementationPartner",
    "Keywords",
    "KickOffDate",
    "OverridingNativeBrowser",
    "Platform",
    "Region",
    "ServerSession",
    "TA",
    "TC",
    "TDDUrl",
    "TechnicalDescription",
    "Url",
    "UseAsReference",
    "UseCXMarketing",
    "UseConsent",
    "UseIdentity",
    "UseProfile",
    "useCXCommerce",
    "useCXSales",
    "useCXServices"
  ],
  template: {
    "UseIdentity": false,
    "UseConsent": false,
    "UseProfile": true,
    "UseCXMarketing": false,
    "UseCXCommerce": false,
    "UseCXSales": false,
    "UseCXServices": false,
    "UseAsReference": false,
    "Implementation": "",
    "ImplementationPartner": "",
    "Url": "",
    "Customer": "",
    'KickOffDate': "",
    'GoLiveDate': "",
    'Created': new Date().toDateString(),
    'AM': "",
    'IC': "",
    'TC': "",
    'TA': "",
    'Country': "",
    'Region': "",
    'Platform': "",
    'Category': "",
    "TDDUrl": "",
    "APIKey": "",
    "CustomFlows": "",
    "CMS": "",
    "ServerSession": "",
    "CentralizedLoginSSO": "",
    "FrontEndLibraries": "",
    "OverridingNativeBrowser": "",
    "Description": "",
    "TechnicalDescription": "",
    "Keywords": [],
    "ImageUrl": "temp.png"
  },
  requiredFields: [
    "Implementation",
    "Customer",
    "Region",
    "Keywords",
    "Description",
    "TechnicalDescription",
    "GoLiveDate",
    "KickOffDate",
    "ImageRef"
  ]
}